//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IniEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IniEditor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow duplicate sections.
        /// </summary>
        internal static string AllowDuplicateSections {
            get {
                return ResourceManager.GetString("AllowDuplicateSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow global keys.
        /// </summary>
        internal static string AllowGlobalKeys {
            get {
                return ResourceManager.GetString("AllowGlobalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space on both sides of delimiter.
        /// </summary>
        internal static string BothSides {
            get {
                return ResourceManager.GetString("BothSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon delimiter (:).
        /// </summary>
        internal static string ColonDelimiter {
            get {
                return ResourceManager.GetString("ColonDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string CommentRule {
            get {
                return ResourceManager.GetString("CommentRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRLF newline.
        /// </summary>
        internal static string CrLfNewline {
            get {
                return ResourceManager.GetString("CrLfNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default environment newline.
        /// </summary>
        internal static string DefaultEnvironmentNewline {
            get {
                return ResourceManager.GetString("DefaultEnvironmentNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallow duplicate keys.
        /// </summary>
        internal static string DisallowDuplicateKeys {
            get {
                return ResourceManager.GetString("DisallowDuplicateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallow duplicate sections.
        /// </summary>
        internal static string DisallowDuplicateSections {
            get {
                return ResourceManager.GetString("DisallowDuplicateSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallow global keys.
        /// </summary>
        internal static string DisallowGlobalKeys {
            get {
                return ResourceManager.GetString("DisallowGlobalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate key adds value.
        /// </summary>
        internal static string DuplicateKeyAddsValue {
            get {
                return ResourceManager.GetString("DuplicateKeyAddsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate key replaces value.
        /// </summary>
        internal static string DuplicateKeyReplacesValue {
            get {
                return ResourceManager.GetString("DuplicateKeyReplacesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate key rule.
        /// </summary>
        internal static string DuplicateKeyRule {
            get {
                return ResourceManager.GetString("DuplicateKeyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate section rule.
        /// </summary>
        internal static string DuplicateSectionRule {
            get {
                return ResourceManager.GetString("DuplicateSectionRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals delimiter (=).
        /// </summary>
        internal static string EqualsDelimiter {
            get {
                return ResourceManager.GetString("EqualsDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals or colon delimiter (=, :).
        /// </summary>
        internal static string EqualsOrColonDelimiter {
            get {
                return ResourceManager.GetString("EqualsOrColonDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequences.
        /// </summary>
        internal static string EscapeSequenceRule {
            get {
                return ResourceManager.GetString("EscapeSequenceRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global keys rule.
        /// </summary>
        internal static string GlobalKeysRule {
            get {
                return ResourceManager.GetString("GlobalKeysRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash and semicolon comments (#, ;).
        /// </summary>
        internal static string HashAndSemicolonComments {
            get {
                return ResourceManager.GetString("HashAndSemicolonComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash comments (#).
        /// </summary>
        internal static string HashComments {
            get {
                return ResourceManager.GetString("HashComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore escape sequences.
        /// </summary>
        internal static string IgnoreEscapeSequences {
            get {
                return ResourceManager.GetString("IgnoreEscapeSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore quotation.
        /// </summary>
        internal static string IgnoreQuotation {
            get {
                return ResourceManager.GetString("IgnoreQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space on left of delimiter.
        /// </summary>
        internal static string LeftOnly {
            get {
                return ResourceManager.GetString("LeftOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF newline.
        /// </summary>
        internal static string LfNewline {
            get {
                return ResourceManager.GetString("LfNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge duplicate section into original.
        /// </summary>
        internal static string MergeDuplicateIntoOriginal {
            get {
                return ResourceManager.GetString("MergeDuplicateIntoOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge original section into duplicate.
        /// </summary>
        internal static string MergeOriginalIntoDuplicate {
            get {
                return ResourceManager.GetString("MergeOriginalIntoDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name value delimiter preference rule.
        /// </summary>
        internal static string NameValueDelimiterPreferenceRule {
            get {
                return ResourceManager.GetString("NameValueDelimiterPreferenceRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name-value delimiter.
        /// </summary>
        internal static string NameValueDelimiterRule {
            get {
                return ResourceManager.GetString("NameValueDelimiterRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name value delimiter spacing rule.
        /// </summary>
        internal static string NameValueDelimiterSpacingRule {
            get {
                return ResourceManager.GetString("NameValueDelimiterSpacingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newline.
        /// </summary>
        internal static string NewlineRule {
            get {
                return ResourceManager.GetString("NewlineRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No delimiter.
        /// </summary>
        internal static string NoDelimiter {
            get {
                return ResourceManager.GetString("NoDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spacing.
        /// </summary>
        internal static string NoSpacing {
            get {
                return ResourceManager.GetString("NoSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer colon delimiter (:).
        /// </summary>
        internal static string PreferColonDelimiter {
            get {
                return ResourceManager.GetString("PreferColonDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer equals delimiter (=).
        /// </summary>
        internal static string PreferEqualsDelimiter {
            get {
                return ResourceManager.GetString("PreferEqualsDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer no delimiter.
        /// </summary>
        internal static string PreferNoDelimiter {
            get {
                return ResourceManager.GetString("PreferNoDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation.
        /// </summary>
        internal static string QuotationRule {
            get {
                return ResourceManager.GetString("QuotationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space on right of delimiter.
        /// </summary>
        internal static string RightOnly {
            get {
                return ResourceManager.GetString("RightOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon comments (;).
        /// </summary>
        internal static string SemicolonComments {
            get {
                return ResourceManager.GetString("SemicolonComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use escape sequences.
        /// </summary>
        internal static string UseEscapeSequences {
            get {
                return ResourceManager.GetString("UseEscapeSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use escape sequences and line continuation.
        /// </summary>
        internal static string UseEscapeSequencesAndLineContinuation {
            get {
                return ResourceManager.GetString("UseEscapeSequencesAndLineContinuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use quotation.
        /// </summary>
        internal static string UseQuotation {
            get {
                return ResourceManager.GetString("UseQuotation", resourceCulture);
            }
        }
    }
}
